variable "vpc_id" {
  type        = string
  description = "id of our VPC in right region"
}

variable "my_ip_with_cidr" {
  type        = string
  description = "Provide your local public IP to firewall ingress ssh rule e.g. 88.103.235.238/32"
}

variable "key_pair_name" {
  type        = string
  description = "name of key-pair to connect ec2, we need pem/ppk in our computer to connect"
}
/*
  variable public_key {
    type = string
    description = "rsa public key for connection via ssh generated by keygen"  
  }
  */


variable "instance_type" {
  type        = string
  description = "type of aws ec2 instance"
  default     = "t2.micro"
}

variable "server_name" {
  type        = string
  description = "name of ec2 instance server"
}
